language: android
sudo: false
jdk:
- oraclejdk8
env:
  global:
   - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.0
  - android-28
  - android-27
  - android-26
  - android-25
  - android-24
  - android-23
  - android-22
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
env:
script:
- "./gradlew detektCustom "
install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"