language: android
sudo: false
jdk:
- oraclejdk8
env:
  global:
   - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.0
  - android-28
  - android-22
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
env:
before_script:
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- sleep 300
- adb shell input keyevent 82 &
script:
- "./gradlew dependencies || true"
- "./gradlew build connectedCheck"
before_install:
    - pip install --user codecov
after_success:
    - codecov
install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
cache:
  before_cache:
  - "rm -fr  $HOME/m2/*"
  - "rm -fr $HOME/.gradle/*"
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"