language: android
sudo: false
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
env:
script:
- travis_wait 30 "./build.sh"
before_script:
- echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- sleep 180
- adb devices
- adb shell input keyevent 82 &
notifications:
  email: true
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"